In [1]:
# ==========================================================
# PROYECTO: PREDICCIÓN DE GRD
# BLOQUE 1: CARGA E INSPECCIÓN INICIAL DEL DATASET PRINCIPAL
# ==========================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings("ignore")
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 120)

# ==========================================================
# PASO 1. CARGA DE ARCHIVOS DEL PROYECTO
# ==========================================================

from google.colab import files
uploaded = files.upload()

# ==========================================================
# PASO 2. DEFINICIÓN DE RUTA DEL DATASET PRINCIPAL
# ==========================================================

dataset_path = "/content/dataset_elpino.csv"
print("Dataset principal:", dataset_path)

# ==========================================================
# PASO 3. LECTURA DEL DATASET PRINCIPAL
# el archivo se separa por ';'
# ==========================================================

df = pd.read_csv(
    dataset_path,
    sep=";",
    encoding="utf-8",
    engine="python"
)

# En caso de presentar problemas con codigo se puede usar el codigo de abajo:
# df = pd.read_csv(
#     dataset_path,
#     sep=";",
#     encoding="latin-1",
#     engine="python"
# )

# ==========================================================
# PASO 4. INSPECCIÓN INICIAL DEL DATASET
# ==========================================================

print("Dimensiones del dataset:", df.shape)

print("\nPrimeras 5 filas:")
display(df.head())

print("\nNombres de columnas:")
print(df.columns.tolist())

print("\nInformación general del dataset:")
df.info()

print("\nValores nulos por columna:")
display(df.isnull().sum())

Saving dataset_elpino.csv to dataset_elpino.csv
Dataset principal: /content/dataset_elpino.csv
Dimensiones del dataset: (14561, 68)

Primeras 5 filas:

,Diag 01 Principal (cod+des),Diag 02 Secundario (cod+des),Diag 03 Secundario (cod+des),Diag 04 Secundario (cod+des),Diag 05 Secundario (cod+des),Diag 06 Secundario (cod+des),Diag 07 Secundario (cod+des),Diag 08 Secundario (cod+des),Diag 09 Secundario (cod+des),Diag 10 Secundario (cod+des),Diag 11 Secundario (cod+des),Diag 12 Secundario (cod+des),Diag 13 Secundario (cod+des),Diag 14 Secundario (cod+des),Diag 15 Secundario (cod+des),Diag 16 Secundario (cod+des),Diag 17 Secundario (cod+des),Diag 18 Secundario (cod+des),Diag 19 Secundario (cod+des),Diag 20 Secundario (cod+des),Diag 21 Secundario (cod+des),Diag 22 Secundario (cod+des),Diag 23 Secundario (cod+des),Diag 24 Secundario (cod+des),Diag 25 Secundario (cod+des),Diag 26 Secundario (cod+des),Diag 27 Secundario (cod+des),Diag 28 Secundario (cod+des),Diag 29 Secundario (cod+des),Diag 30 Secundario (cod+des),Diag 31 Secundario (cod+des),Diag 32 Secundario (cod+des),Diag 33 Secundario (cod+des),Diag 34 Secundario (cod+des),Diag 35 Secundario (cod+des),Proced 01 Principal (cod+des),Proced 02 Secundario (cod+des),Proced 03 Secundario (cod+des),Proced 04 Secundario (cod+des),Proced 05 Secundario (cod+des),Proced 06 Secundario (cod+des),Proced 07 Secundario (cod+des),Proced 08 Secundario (cod+des),Proced 09 Secundario (cod+des),Proced 10 Secundario (cod+des),Proced 11 Secundario (cod+des),Proced 12 Secundario (cod+des),Proced 13 Secundario (cod+des),Proced 14 Secundario (cod+des),Proced 15 Secundario (cod+des),Proced 16 Secundario (cod+des),Proced 17 Secundario (cod+des),Proced 18 Secundario (cod+des),Proced 19 Secundario (cod+des),Proced 20 Secundario (cod+des),Proced 21 Secundario (cod+des),Proced 22 Secundario (cod+des),Proced 23 Secundario (cod+des),Proced 24 Secundario (cod+des),Proced 25 Secundario (cod+des),Proced 26 Secundario (cod+des),Proced 27 Secundario (cod+des),Proced 28 Secundario (cod+des),Proced 29 Secundario (cod+des),Proced 30 Secundario (cod+des),Edad en años,Sexo (Desc),GRD
0,A41.8 - Otras septicemias especificadas,B37.6 - Endocarditis debida a candida (I39.8*),"I39.8 - Endocarditis, válvula no especificada, en enfermedades clasificadas en otra parte",N10 - Nefritis tubulointersticial aguda,B96.1 - Klebsiella pneumoniae [K. pneumoniae] como causa de enfermedades clasificadas en otros capítulos,L89.9 - Úlcera de decúbito y area de presión no especificadas,"L08.9 - Infección local de la piel y del tejido subcutáneo, no especificada",B96.2 - Escherichia coli [E. coli] como causa de enfermedades clasificadas en otros capítulos,A41.5 - Sepsis por otros organnismos Gram negativos,J86.9 - Piotórax sin fístula,"U07.1 - COVID-19, virus identificado",Y95 - Afección nosocomial,"N18.5 - Enfermedad renal crónica, estadio 5",E87.1 - Hiposmolaridad e hiponatremia,D64.9 - Anemia de tipo no especificado,"G82.2 - Paraplejía, no especificada","N31.9 - Disfunción neuromuscular de la vejiga, no especificada",I10 - Hipertensión esencial (primaria),K70.4 - Insuficiencia hepática alcohólica,F19.2 - Trastornos mentales y del comportamiento debidos al uso de múltiples drogas y al uso de otras sustancias psi...,"F10.2 - Trastornos mentales y del comportamiento debidos al uso de alcohol, síndrome de dependencia","E46 - Desnutrición proteicocalórica, no especificada","G40.9 - Epilepsia, tipo no especificado","L21.9 - Dermatitis seborreica, no especificada",Z93.5 - Cistostomía,Z93.3 - Colostomía,Z99.2 - Dependencia de diálisis renal,Z91.6 - Historia personal de otro trauma físico,-,-,-,-,-,-,-,"86.28 - DESBRIDAMIENTO HERIDA,INFECCION O QUEMADURA NO ESCISIONAL",34.91 - TORACOCENTESIS,88.38 - TOMOGRAFIA AXIAL COMPUTERIZADA OTRA,87.41 - TOMOGRAFIA AXIAL COMPUTERIZADA TORAX,88.75 - ECOGRAFIA APARATO URINARIO,88.01 - TOMOGRAFIA AXIAL COMPUTERIZADA ABDOMEN,88.43 - ARTERIOGRAFIA ARTERIA PULMONAR,88.41 - ARTERIOGRAFIA ARTERIA CEREBRAL,87.44 - RADIOGRAFIA TORAX RUTINARIA,99.29 - INYECCION SUSTANCIA TERAPEUTICA O PROFILACTICA.OTRA,99.19 - INYECCION ANTICOAGULANTE,99.18 - INYECCION ELECTROLITO,99.21 - INYECCION ANTIBIOTICO,99.26 - INYECCION TRANQUILIZANTE,99.23 - INYECCION ESTEROIDE,93.94 - AEROSOLTERAPIA,89.52 - ELECTROCARDIOGRAFIA,90.59 - EXAMEN MICROSCOPICO SANGRE.OTRO,89.65 - GASOMETRIA ARTERIA,39.95 - HEMODIALISIS,39.95 - HEMODIALISIS,99.04 - TRANSFUSION CONCENTRADO HEMATIES,90.39 - EXAMEN MICROSCOPICO ORL.OTRO,99.84 - AISLAMIENTO,88.72 - ECOCARDIOGRAFIA,90.42 - EXAMEN MICROSCOPICO RESPIRATORIO.CULTIVO,90.52 - EXAMEN MICROSCOPICO SANGRE.CULTIVO,91.39 - EXAMEN MICROSCOPICO URINARIO INFERIOR.OTRO,91.33 - EXAMEN MICROSCOPICO URINARIO INFERIOR.CULTIVO Y SENSIBILIDAD,87.03 - TOMOGRAFIA AXIAL COMPUTERIZADA CABEZA,40,Hombre,184103 - MH SEPTICEMIA W/MCC
1,"U07.1 - COVID-19, virus identificado",J12.8 - Neumonía debida a otros virus,R06.0 - Disnea,R05 - Tos,"R50.9 - Fiebre, no especificada",Z29.0 - Aislamiento,Z01.7 - Examen de laboratorio,"J96.00 - Insuficiencia respiratoria aguda, Tipo I (hipoxémica)",J94.2 - Hemotórax,J92.9 - Paquipleuritis sin asbestosis,J15.1 - Neumonía debida a Pseudomonas,Y95 - Afección nosocomial,"N17.9 - Insuficiencia renal aguda, no especificada",G62.8 - Otras polineuropatías especificadas,"M54.19 - Radiculopatía, sitio no especificado",L89.3 - Úlcera de decúbito estadio IV,"F13.2 - Trastornos mentales y del comportamiento debidos al uso de sedantes o hipnóticos, síndrome de dependencia",-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,31.1 - TRAQUEOSTOMIA TEMPORAL,"86.28 - DESBRIDAMIENTO HERIDA,INFECCION O QUEMADURA NO ESCISIONAL",96.72 - VENTILACION MECANICA CONTINUA OTRA.DURANTE 96 HORAS O MAS,93.90 - RESPIRACION PRESION POSITIVA CONTINUA [RPPC],89.7 - EXAMEN FISICO GENERAL,88.01 - TOMOGRAFIA AXIAL COMPUTERIZADA ABDOMEN,87.41 - TOMOGRAFIA AXIAL COMPUTERIZADA TORAX,34.04 - INTUBACION INTERCOSTAL PARA DRENAJE,88.43 - ARTERIOGRAFIA ARTERIA PULMONAR,93.96 - ENRIQUECIMIENTO OXIGENO OTRO,93.94 - AEROSOLTERAPIA,90.39 - EXAMEN MICROSCOPICO ORL.OTRO,99.84 - AISLAMIENTO,99.29 - INYECCION SUSTANCIA TERAPEUTICA O PROFILACTICA.OTRA,99.19 - INYECCION ANTICOAGULANTE,00.17 - INFUSON AGENTE VASOPRESOR,99.21 - INYECCION ANTIBIOTICO,99.18 - INYECCION ELECTROLITO,99.26 - INYECCION TRANQUILIZANTE,99.23 - INYECCION ESTEROIDE,89.65 - GASOMETRIA ARTERIA,91.69 - EXAMEN MICROSCOPICO PIEL.OTRO,87.44 - RADIOGRAFIA TORAX RUTINARIA,91.62 - EXAMEN MICROSCOPICO PIEL.CULTIVO,90.43 - EXAMEN MICROSCOPICO RESPIRATORIO.CULTIVO Y SENSIBILIDAD,91.39 - EXAMEN MICROSCOPICO URINARIO INFERIOR.OTRO,90.52 - EXAMEN MICROSCOPICO SANGRE.CULTIVO,91.32 - EXAMEN MICROSCOPICO URINARIO INFERIOR.CULTIVO,96.59 - IRRIGACION HERIDA OTRA,90.99 - EXAMEN MICROSCOPICO DIGESTIVO INFERIOR.OTRO,53,Hombre,041013 - PH ECMO VENTILACIÓN MECÁNICA PROLONGADA CON TRAQUEOSTOMÍA W/MCC
2,K56.5 - Adherencias [bridas] intestinales con obstrucción,R57.2 - Shock séptico,R57.1 - Choque hipovolémico,J80 - Síndrome de dificultad respiratoria del adulto,Y95 - Afección nosocomial,J15.0 - Neumonía debida a Klebsiella pneumoniae,U82.2 - Resistencia a Betalactamasas de amplio espectro,B95.6 - Staphylococcus aureus como causa de enfermedades clasificadas en otros capítulos,B96.8 - Otros agentes bacterianos especificados como causa de enfermedades clasificadas en otros capítulos,B37.1 - Candidiasis pulmonar,J99.8 - Trastornos respiratorios en otras enfermedades clasificadas en otra parte,J69.0 - Neumonitis debida a aspiración de alimento o vómito,"A49.0 - Infección estafilocócica, de sitio no especificado",L89.3 - Úlcera de decúbito estadio IV,B96.4 - Proteus (mirabilis) (morganii) como causa de enfermedades clasificadas en otros capítulos,E11.1 - Diabetes mellitus tipo 2 con cetoacidosis,E87.0 - Hiperosmolaridad e hipernatremia,E87.6 - Hipopotasmia,E83.5 - Trastornos del metabolismo del calcio,"N17.9 - Insuficiencia renal aguda, no especificada","K75.9 - Enfermedad inflamatoria del hígado, no especificada",D64.9 - Anemia de tipo no especificado,"E46 - Desnutrición proteicocalórica, no especificada",E87.3 - Alcalosis,J44.8 - Otras enfermedades pulmonares obstructivas crónicas especificadas,J98.4 - Otros trastornos del pulmón,"U07.1 - COVID-19, virus identificado",Z29.0 - Aislamiento,Z01.7 - Examen de laboratorio,Z20.8 - Contacto con y exposición a otras enfermedades transmisibles,Z88.0 - Historia personal de alergia a penicilina,Z72.0 - Problemas relacionados con el uso del tabaco,-,-,-,"86.22 - DESBRIDAMIENTO HERIDA,INFECCION O QUEMADURA ESCISIONAL",54.59 - LISIS ADHERENCIA PERITONEO.OTRA,96.72 - VENTILACION MECANICA CONTINUA OTRA.DURANTE 96 HORAS O MAS,31.1 - TRAQUEOSTOMIA TEMPORAL,45.13 - ESOFAGOGASTRODUODENOSCOPIA [EGD],87.41 - TOMOGRAFIA AXIAL COMPUTERIZADA TORAX,87.03 - TOMOGRAFIA AXIAL COMPUTERIZADA CABEZA,88.01 - TOMOGRAFIA AXIAL COMPUTERIZADA ABDOMEN,88.43 - ARTERIOGRAFIA ARTERIA PULMONAR,88.72 - ECOCARDIOGRAFIA,33.22 - BRONCOSCOPIA FLEXIBLE,87.44 - RADIOGRAFIA TORAX RUTINARIA,89.7 - EXAMEN FISICO GENERAL,90.59 - EXAMEN MICROSCOPICO SANGRE.OTRO,00.17 - INFUSON AGENTE VASOPRESOR,99.21 - INYECCION ANTIBIOTICO,99.04 - TRANSFUSION CONCENTRADO HEMATIES,93.96 - ENRIQUECIMIENTO OXIGENO OTRO,91.83 - EXAMEN MICROSCOPICO OTRO.CULTIVO Y SENSIBILIDAD,90.43 - EXAMEN MICROSCOPICO RESPIRATORIO.CULTIVO Y SENSIBILIDAD,38.93 - CATETERISMO VENA OTRO,91.33 - EXAMEN MICROSCOPICO URINARIO INFERIOR.CULTIVO Y SENSIBILIDAD,90.39 - EXAMEN MICROSCOPICO ORL.OTRO,99.84 - AISLAMIENTO,91.73 - EXAMEN MICROSCOPICO HERIDA OPERATORIA.CULTIVO Y SENSIBILIDAD,90.53 - EXAMEN MICROSCOPICO SANGRE.CULTIVO Y SENSIBILIDAD,99.26 - INYECCION TRANQUILIZANTE,89.39 - OTRAS MEDICIONES Y EXAMENES NO QUIRURGICOS,89.66 - GASOMETRIA VENA,89.65 - GASOMETRIA ARTERIA,65,Hombre,041013 - PH ECMO VENTILACIÓN MECÁNICA PROLONGADA CON TRAQUEOSTOMÍA W/MCC
3,K76.8 - Otras enfermedades especificadas del hígado,K66.1 - Hemoperitoneo,"N18.5 - Enfermedad renal crónica, estadio 5",D64.9 - Anemia de tipo no especificado,E87.5 - Hiperpotasemia,E87.2 - Acidosis,J81 - Edema pulmonar,N17.8 - Otras insuficiencias renales agudas,"J44.9 - Enfermedad pulmonar obstructiva crónica, no especificada",R41.0 - Desorientación no especificada,K44.9 - Hernia diafragmática sin obstrucción ni gangrena,"K26.9 - Úlcera duodenal, no especificada como aguda ni crónica, sin hemorragia ni perforación",B96.2 - Escherichia coli [E. coli] como causa de enfermedades clasificadas en otros capítulos,R57.1 - Choque hipovolémico,K80.2 - Cálculo de la vesícula biliar sin colecistitis,L89.0 - Úlcera de decúbito y area de presión estadío I,"F12.2 - Trastornos mentales y del comportamiento debidos al uso de cannabinoides, síndrome de dependencia",Z91.1 - Historia personal de incumplimiento del régimen o tratamiento médico,Z99.2 - Dependencia de diálisis renal,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,54.19 - LAPAROTOMIA.OTRA,39.98 - CONTROL HEMORRAGIA NEOM,"86.28 - DESBRIDAMIENTO HERIDA,INFECCION O QUEMADURA NO ESCISIONAL",54.62 - CIERRE DIFERIDO HERIDA ABDOMEN EN GRANULACION,96.72 - VENTILACION MECANICA CONTINUA OTRA.DURANTE 96 HORAS O MAS,96.04 - INTUBACION ENDOTRAQUEAL,87.41 - TOMOGRAFIA AXIAL COMPUTERIZADA TORAX,88.01 - TOMOGRAFIA AXIAL COMPUTERIZADA ABDOMEN,88.38 - TOMOGRAFIA AXIAL COMPUTERIZADA OTRA,88.41 - ARTERIOGRAFIA ARTERIA CEREBRAL,88.47 - ARTERIOGRAFIA ARTERIA INTRABDOMINAL OTRA,87.44 - RADIOGRAFIA TORAX RUTINARIA,88.75 - ECOGRAFIA APARATO URINARIO,88.79 - ECOGRAFIA OTRA,88.72 - ECOCARDIOGRAFIA,89.52 - ELECTROCARDIOGRAFIA,45.13 - ESOFAGOGASTRODUODENOSCOPIA [EGD],38.93 - CATETERISMO VENA OTRO,38.91 - CATETERISMO ARTERIA,38.95 - CATETERISMO VENA PARA DIALISIS RIÑON,39.95 - HEMODIALISIS,96.59 - IRRIGACION HERIDA OTRA,94.19 - ENTREVISTA Y EVALUACION PSIQUIATRICA.OTRA,57.94 - SONDAJE URINARIO PERMANENTE,00.13 - INYECCION NESIRITIDE,00.17 - INFUSON AGENTE VASOPRESOR,99.04 - TRANSFUSION CONCENTRADO HEMATIES,99.18 - INYECCION ELECTROLITO,99.21 - INYECCION ANTIBIOTICO,99.23 - INYECCION ESTEROIDE,61,Hombre,041023 - PH VENTILACIÓN MECÁNICA PROLONGADA SIN TRAQUEOSTOMÍA W/MCC
4,"T81.0 - Hemorragia y hematoma que complican un procedimiento, no clasificados en otra parte","Y83.2 - Operación quirúrgica con anastomosis, derivación o injerto",S31.1 - Herida de la pared abdominal,"S36.80 - Traumatismo de otros órganos intraabdominales, sin herida dentro de la cavidad abdominal","W31.62 - Contacto traumático con otras maquinarias, y las no especificadas, área industrial y de la construcción, mi...","J96.09 - Insuficiencia respiratoria aguda, Tipo no especificado",J15.0 - Neumonía debida a Klebsiella pneumoniae,U82.2 - Resistencia a Betalactamasas de amplio espectro,"U07.1 - COVID-19, virus identificado","N39.0 - Infección de vías urinarias, sitio no especificado",B96.2 - Escherichia coli [E. coli] como causa de enfermedades clasificadas en otros capítulos,Y95 - Afección nosocomial,D62 - Anemia posthemorrágica aguda,"N17.9 - Insuficiencia renal aguda, no especificada",E87.6 - Hipopotasmia,K70.4 - Insuficiencia hepática alcohólica,I85.9 - Várices esofágicas sin hemorragia,G93.4 - Encefalopatía no especificada,R18 - Ascitis,I10 - Hipertensión esencial (primaria),"F10.2 - Trastornos mentales y del comportamiento debidos al uso de alcohol, síndrome de dependencia",F19.2 - Trastornos mentales y del comportamiento debidos al uso de múltiples drogas y al uso de otras sustancias psi...,-,-,-,-,-,-,-,-,-,-,-,-,-,54.11 - LAPAROTOMIA EXPLORATORIA,45.90 - ANASTOMOSIS INTESTINO.NEOM,46.73 - SUTURA INTESTINO DELGADO SALVO DUODENO,46.20 - ILEOSTOMIA.NEOM,"86.28 - DESBRIDAMIENTO HERIDA,INFECCION O QUEMADURA NO ESCISIONAL",54.19 - LAPAROTOMIA.OTRA,89.7 - EXAMEN FISICO GENERAL,96.04 - INTUBACION ENDOTRAQUEAL,96.72 - VENTILACION MECANICA CONTINUA OTRA.DURANTE 96 HORAS O MAS,54.4 - ESCISION PERITONEO LOCAL,88.47 - ARTERIOGRAFIA ARTERIA INTRABDOMINAL OTRA,88.01 - TOMOGRAFIA AXIAL COMPUTERIZADA ABDOMEN,87.44 - RADIOGRAFIA TORAX RUTINARIA,99.04 - TRANSFUSION CONCENTRADO HEMATIES,93.94 - AEROSOLTERAPIA,93.96 - ENRIQUECIMIENTO OXIGENO OTRO,00.13 - INYECCION NESIRITIDE,00.17 - INFUSON AGENTE VASOPRESOR,99.18 - INYECCION ELECTROLITO,99.26 - INYECCION TRANQUILIZANTE,99.19 - INYECCION ANTICOAGULANTE,99.21 - INYECCION ANTIBIOTICO,99.29 - INYECCION SUSTANCIA TERAPEUTICA O PROFILACTICA.OTRA,90.52 - EXAMEN MICROSCOPICO SANGRE.CULTIVO,91.39 - EXAMEN MICROSCOPICO URINARIO INFERIOR.OTRO,91.32 - EXAMEN MICROSCOPICO URINARIO INFERIOR.CULTIVO,93.90 - RESPIRACION PRESION POSITIVA CONTINUA [RPPC],99.15 - INFUSION PARENTERAL SUSTANCIA NUTRITIVA CONCENTRADA,96.59 - IRRIGACION HERIDA OTRA,45.13 - ESOFAGOGASTRODUODENOSCOPIA [EGD],30,Hombre,041023 - PH VENTILACIÓN MECÁNICA PROLONGADA SIN TRAQUEOSTOMÍA W/MCC

Nombres de columnas:
['Diag 01 Principal (cod+des)', 'Diag 02 Secundario (cod+des)', 'Diag 03 Secundario (cod+des)', 'Diag 04 Secundario (cod+des)', 'Diag 05 Secundario (cod+des)', 'Diag 06 Secundario (cod+des)', 'Diag 07 Secundario (cod+des)', 'Diag 08 Secundario (cod+des)', 'Diag 09 Secundario (cod+des)', 'Diag 10 Secundario (cod+des)', 'Diag 11 Secundario (cod+des)', 'Diag 12 Secundario (cod+des)', 'Diag 13 Secundario (cod+des)', 'Diag 14 Secundario (cod+des)', 'Diag 15 Secundario (cod+des)', 'Diag 16 Secundario (cod+des)', 'Diag 17 Secundario (cod+des)', 'Diag 18 Secundario (cod+des)', 'Diag 19 Secundario (cod+des)', 'Diag 20 Secundario (cod+des)', 'Diag 21 Secundario (cod+des)', 'Diag 22 Secundario (cod+des)', 'Diag 23 Secundario (cod+des)', 'Diag 24 Secundario (cod+des)', 'Diag 25 Secundario (cod+des)', 'Diag 26 Secundario (cod+des)', 'Diag 27 Secundario (cod+des)', 'Diag 28 Secundario (cod+des)', 'Diag 29 Secundario (cod+des)', 'Diag 30 Secundario (cod+des)', 'Diag 31 Secundario (cod+des)', 'Diag 32 Secundario (cod+des)', 'Diag 33 Secundario (cod+des)', 'Diag 34 Secundario (cod+des)', 'Diag 35 Secundario (cod+des)', 'Proced 01 Principal (cod+des)', 'Proced 02 Secundario (cod+des)', 'Proced 03 Secundario (cod+des)', 'Proced 04 Secundario (cod+des)', 'Proced 05 Secundario (cod+des)', 'Proced 06 Secundario (cod+des)', 'Proced 07 Secundario (cod+des)', 'Proced 08 Secundario (cod+des)', 'Proced 09 Secundario (cod+des)', 'Proced 10 Secundario (cod+des)', 'Proced 11 Secundario (cod+des)', 'Proced 12 Secundario (cod+des)', 'Proced 13 Secundario (cod+des)', 'Proced 14 Secundario (cod+des)', 'Proced 15 Secundario (cod+des)', 'Proced 16 Secundario (cod+des)', 'Proced 17 Secundario (cod+des)', 'Proced 18 Secundario (cod+des)', 'Proced 19 Secundario (cod+des)', 'Proced 20 Secundario (cod+des)', 'Proced 21 Secundario (cod+des)', 'Proced 22 Secundario (cod+des)', 'Proced 23 Secundario (cod+des)', 'Proced 24 Secundario (cod+des)', 'Proced 25 Secundario (cod+des)', 'Proced 26 Secundario (cod+des)', 'Proced 27 Secundario (cod+des)', 'Proced 28 Secundario (cod+des)', 'Proced 29 Secundario (cod+des)', 'Proced 30 Secundario (cod+des)', 'Edad en años', 'Sexo (Desc)', 'GRD']

Información general del dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14561 entries, 0 to 14560
Data columns (total 68 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Diag 01 Principal (cod+des)     14561 non-null  object
 1   Diag 02 Secundario (cod+des)    14561 non-null  object
 2   Diag 03 Secundario (cod+des)    14561 non-null  object
 3   Diag 04 Secundario (cod+des)    14561 non-null  object
 4   Diag 05 Secundario (cod+des)    14561 non-null  object
 5   Diag 06 Secundario (cod+des)    14561 non-null  object
 6   Diag 07 Secundario (cod+des)    14561 non-null  object
 7   Diag 08 Secundario (cod+des)    14561 non-null  object
 8   Diag 09 Secundario (cod+des)    14561 non-null  object
 9   Diag 10 Secundario (cod+des)    14561 non-null  object
 10  Diag 11 Secundario (cod+des)    14561 non-null  object
 11  Diag 12 Secundario (cod+des)    14561 non-null  object
 12  Diag 13 Secundario (cod+des)    14561 non-null  object
 13  Diag 14 Secundario (cod+des)    14561 non-null  object
 14  Diag 15 Secundario (cod+des)    14561 non-null  object
 15  Diag 16 Secundario (cod+des)    14561 non-null  object
 16  Diag 17 Secundario (cod+des)    14561 non-null  object
 17  Diag 18 Secundario (cod+des)    14561 non-null  object
 18  Diag 19 Secundario (cod+des)    14561 non-null  object
 19  Diag 20 Secundario (cod+des)    14561 non-null  object
 20  Diag 21 Secundario (cod+des)    14561 non-null  object
 21  Diag 22 Secundario (cod+des)    14561 non-null  object
 22  Diag 23 Secundario (cod+des)    14561 non-null  object
 23  Diag 24 Secundario (cod+des)    14561 non-null  object
 24  Diag 25 Secundario (cod+des)    14561 non-null  object
 25  Diag 26 Secundario (cod+des)    14561 non-null  object
 26  Diag 27 Secundario (cod+des)    14561 non-null  object
 27  Diag 28 Secundario (cod+des)    14561 non-null  object
 28  Diag 29 Secundario (cod+des)    14561 non-null  object
 29  Diag 30 Secundario (cod+des)    14561 non-null  object
 30  Diag 31 Secundario (cod+des)    14561 non-null  object
 31  Diag 32 Secundario (cod+des)    14561 non-null  object
 32  Diag 33 Secundario (cod+des)    14561 non-null  object
 33  Diag 34 Secundario (cod+des)    14561 non-null  object
 34  Diag 35 Secundario (cod+des)    14561 non-null  object
 35  Proced 01 Principal (cod+des)   14561 non-null  object
 36  Proced 02 Secundario (cod+des)  14561 non-null  object
 37  Proced 03 Secundario (cod+des)  14561 non-null  object
 38  Proced 04 Secundario (cod+des)  14561 non-null  object
 39  Proced 05 Secundario (cod+des)  14561 non-null  object
 40  Proced 06 Secundario (cod+des)  14561 non-null  object
 41  Proced 07 Secundario (cod+des)  14561 non-null  object
 42  Proced 08 Secundario (cod+des)  14561 non-null  object
 43  Proced 09 Secundario (cod+des)  14561 non-null  object
 44  Proced 10 Secundario (cod+des)  14561 non-null  object
 45  Proced 11 Secundario (cod+des)  14561 non-null  object
 46  Proced 12 Secundario (cod+des)  14561 non-null  object
 47  Proced 13 Secundario (cod+des)  14561 non-null  object
 48  Proced 14 Secundario (cod+des)  14561 non-null  object
 49  Proced 15 Secundario (cod+des)  14561 non-null  object
 50  Proced 16 Secundario (cod+des)  14561 non-null  object
 51  Proced 17 Secundario (cod+des)  14561 non-null  object
 52  Proced 18 Secundario (cod+des)  14561 non-null  object
 53  Proced 19 Secundario (cod+des)  14561 non-null  object
 54  Proced 20 Secundario (cod+des)  14561 non-null  object
 55  Proced 21 Secundario (cod+des)  14561 non-null  object
 56  Proced 22 Secundario (cod+des)  14561 non-null  object
 57  Proced 23 Secundario (cod+des)  14561 non-null  object
 58  Proced 24 Secundario (cod+des)  14561 non-null  object
 59  Proced 25 Secundario (cod+des)  14561 non-null  object
 60  Proced 26 Secundario (cod+des)  14561 non-null  object
 61  Proced 27 Secundario (cod+des)  14561 non-null  object
 62  Proced 28 Secundario (cod+des)  14561 non-null  object
 63  Proced 29 Secundario (cod+des)  14561 non-null  object
 64  Proced 30 Secundario (cod+des)  14561 non-null  object
 65  Edad en años                    14561 non-null  int64
 66  Sexo (Desc)                     14561 non-null  object
 67  GRD                             14561 non-null  object
dtypes: int64(1), object(67)
memory usage: 7.6+ MB

Valores nulos por columna:

Diag 01 Principal (cod+des)       0
Diag 02 Secundario (cod+des)      0
Diag 03 Secundario (cod+des)      0
Diag 04 Secundario (cod+des)      0
Diag 05 Secundario (cod+des)      0
                                 ..
Proced 29 Secundario (cod+des)    0
Proced 30 Secundario (cod+des)    0
Edad en años                      0
Sexo (Desc)                       0
GRD                               0
Length: 68, dtype: int64

In [2]:
# ==========================================================
# PASO 5. IDENTIFICACIÓN DE COLUMNAS CLAVE
# ==========================================================

print("Cantidad total de columnas:", len(df.columns))
print("\nListado completo de columnas:\n")
for i, col in enumerate(df.columns, 1):
    print(f"{i}. {col}")

Cantidad total de columnas: 68

Listado completo de columnas:

1. Diag 01 Principal (cod+des)
2. Diag 02 Secundario (cod+des)
3. Diag 03 Secundario (cod+des)
4. Diag 04 Secundario (cod+des)
5. Diag 05 Secundario (cod+des)
6. Diag 06 Secundario (cod+des)
7. Diag 07 Secundario (cod+des)
8. Diag 08 Secundario (cod+des)
9. Diag 09 Secundario (cod+des)
10. Diag 10 Secundario (cod+des)
11. Diag 11 Secundario (cod+des)
12. Diag 12 Secundario (cod+des)
13. Diag 13 Secundario (cod+des)
14. Diag 14 Secundario (cod+des)
15. Diag 15 Secundario (cod+des)
16. Diag 16 Secundario (cod+des)
17. Diag 17 Secundario (cod+des)
18. Diag 18 Secundario (cod+des)
19. Diag 19 Secundario (cod+des)
20. Diag 20 Secundario (cod+des)
21. Diag 21 Secundario (cod+des)
22. Diag 22 Secundario (cod+des)
23. Diag 23 Secundario (cod+des)
24. Diag 24 Secundario (cod+des)
25. Diag 25 Secundario (cod+des)
26. Diag 26 Secundario (cod+des)
27. Diag 27 Secundario (cod+des)
28. Diag 28 Secundario (cod+des)
29. Diag 29 Secundario (cod+des)
30. Diag 30 Secundario (cod+des)
31. Diag 31 Secundario (cod+des)
32. Diag 32 Secundario (cod+des)
33. Diag 33 Secundario (cod+des)
34. Diag 34 Secundario (cod+des)
35. Diag 35 Secundario (cod+des)
36. Proced 01 Principal (cod+des)
37. Proced 02 Secundario (cod+des)
38. Proced 03 Secundario (cod+des)
39. Proced 04 Secundario (cod+des)
40. Proced 05 Secundario (cod+des)
41. Proced 06 Secundario (cod+des)
42. Proced 07 Secundario (cod+des)
43. Proced 08 Secundario (cod+des)
44. Proced 09 Secundario (cod+des)
45. Proced 10 Secundario (cod+des)
46. Proced 11 Secundario (cod+des)
47. Proced 12 Secundario (cod+des)
48. Proced 13 Secundario (cod+des)
49. Proced 14 Secundario (cod+des)
50. Proced 15 Secundario (cod+des)
51. Proced 16 Secundario (cod+des)
52. Proced 17 Secundario (cod+des)
53. Proced 18 Secundario (cod+des)
54. Proced 19 Secundario (cod+des)
55. Proced 20 Secundario (cod+des)
56. Proced 21 Secundario (cod+des)
57. Proced 22 Secundario (cod+des)
58. Proced 23 Secundario (cod+des)
59. Proced 24 Secundario (cod+des)
60. Proced 25 Secundario (cod+des)
61. Proced 26 Secundario (cod+des)
62. Proced 27 Secundario (cod+des)
63. Proced 28 Secundario (cod+des)
64. Proced 29 Secundario (cod+des)
65. Proced 30 Secundario (cod+des)
66. Edad en años
67. Sexo (Desc)
68. GRD

In [3]:
# ==========================================================
# PASO 6. SEPARACIÓN DE COLUMNAS POR TIPO
# ==========================================================

diag_cols = [col for col in df.columns if "Diag" in col]
proc_cols = [col for col in df.columns if "Proced" in col]
edad_cols = [col for col in df.columns if "Edad" in col]
sexo_cols = [col for col in df.columns if "Sexo" in col]
target_cols = [col for col in df.columns if "GRD" in col]

print("Columnas de diagnósticos:", len(diag_cols))
print(diag_cols)

print("\nColumnas de procedimientos:", len(proc_cols))
print(proc_cols)

print("\nColumnas de edad:")
print(edad_cols)

print("\nColumnas de sexo:")
print(sexo_cols)

print("\nColumna(s) objetivo:")
print(target_cols)

Columnas de diagnósticos: 35
['Diag 01 Principal (cod+des)', 'Diag 02 Secundario (cod+des)', 'Diag 03 Secundario (cod+des)', 'Diag 04 Secundario (cod+des)', 'Diag 05 Secundario (cod+des)', 'Diag 06 Secundario (cod+des)', 'Diag 07 Secundario (cod+des)', 'Diag 08 Secundario (cod+des)', 'Diag 09 Secundario (cod+des)', 'Diag 10 Secundario (cod+des)', 'Diag 11 Secundario (cod+des)', 'Diag 12 Secundario (cod+des)', 'Diag 13 Secundario (cod+des)', 'Diag 14 Secundario (cod+des)', 'Diag 15 Secundario (cod+des)', 'Diag 16 Secundario (cod+des)', 'Diag 17 Secundario (cod+des)', 'Diag 18 Secundario (cod+des)', 'Diag 19 Secundario (cod+des)', 'Diag 20 Secundario (cod+des)', 'Diag 21 Secundario (cod+des)', 'Diag 22 Secundario (cod+des)', 'Diag 23 Secundario (cod+des)', 'Diag 24 Secundario (cod+des)', 'Diag 25 Secundario (cod+des)', 'Diag 26 Secundario (cod+des)', 'Diag 27 Secundario (cod+des)', 'Diag 28 Secundario (cod+des)', 'Diag 29 Secundario (cod+des)', 'Diag 30 Secundario (cod+des)', 'Diag 31 Secundario (cod+des)', 'Diag 32 Secundario (cod+des)', 'Diag 33 Secundario (cod+des)', 'Diag 34 Secundario (cod+des)', 'Diag 35 Secundario (cod+des)']

Columnas de procedimientos: 30
['Proced 01 Principal (cod+des)', 'Proced 02 Secundario (cod+des)', 'Proced 03 Secundario (cod+des)', 'Proced 04 Secundario (cod+des)', 'Proced 05 Secundario (cod+des)', 'Proced 06 Secundario (cod+des)', 'Proced 07 Secundario (cod+des)', 'Proced 08 Secundario (cod+des)', 'Proced 09 Secundario (cod+des)', 'Proced 10 Secundario (cod+des)', 'Proced 11 Secundario (cod+des)', 'Proced 12 Secundario (cod+des)', 'Proced 13 Secundario (cod+des)', 'Proced 14 Secundario (cod+des)', 'Proced 15 Secundario (cod+des)', 'Proced 16 Secundario (cod+des)', 'Proced 17 Secundario (cod+des)', 'Proced 18 Secundario (cod+des)', 'Proced 19 Secundario (cod+des)', 'Proced 20 Secundario (cod+des)', 'Proced 21 Secundario (cod+des)', 'Proced 22 Secundario (cod+des)', 'Proced 23 Secundario (cod+des)', 'Proced 24 Secundario (cod+des)', 'Proced 25 Secundario (cod+des)', 'Proced 26 Secundario (cod+des)', 'Proced 27 Secundario (cod+des)', 'Proced 28 Secundario (cod+des)', 'Proced 29 Secundario (cod+des)', 'Proced 30 Secundario (cod+des)']

Columnas de edad:
['Edad en años']

Columnas de sexo:
['Sexo (Desc)']

Columna(s) objetivo:
['GRD']

In [4]:
# ==========================================================
# PASO 7. INFORMACIÓN GENERAL DEL DATASET
# ==========================================================

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14561 entries, 0 to 14560
Data columns (total 68 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Diag 01 Principal (cod+des)     14561 non-null  object
 1   Diag 02 Secundario (cod+des)    14561 non-null  object
 2   Diag 03 Secundario (cod+des)    14561 non-null  object
 3   Diag 04 Secundario (cod+des)    14561 non-null  object
 4   Diag 05 Secundario (cod+des)    14561 non-null  object
 5   Diag 06 Secundario (cod+des)    14561 non-null  object
 6   Diag 07 Secundario (cod+des)    14561 non-null  object
 7   Diag 08 Secundario (cod+des)    14561 non-null  object
 8   Diag 09 Secundario (cod+des)    14561 non-null  object
 9   Diag 10 Secundario (cod+des)    14561 non-null  object
 10  Diag 11 Secundario (cod+des)    14561 non-null  object
 11  Diag 12 Secundario (cod+des)    14561 non-null  object
 12  Diag 13 Secundario (cod+des)    14561 non-null  object
 13  Diag 14 Secundario (cod+des)    14561 non-null  object
 14  Diag 15 Secundario (cod+des)    14561 non-null  object
 15  Diag 16 Secundario (cod+des)    14561 non-null  object
 16  Diag 17 Secundario (cod+des)    14561 non-null  object
 17  Diag 18 Secundario (cod+des)    14561 non-null  object
 18  Diag 19 Secundario (cod+des)    14561 non-null  object
 19  Diag 20 Secundario (cod+des)    14561 non-null  object
 20  Diag 21 Secundario (cod+des)    14561 non-null  object
 21  Diag 22 Secundario (cod+des)    14561 non-null  object
 22  Diag 23 Secundario (cod+des)    14561 non-null  object
 23  Diag 24 Secundario (cod+des)    14561 non-null  object
 24  Diag 25 Secundario (cod+des)    14561 non-null  object
 25  Diag 26 Secundario (cod+des)    14561 non-null  object
 26  Diag 27 Secundario (cod+des)    14561 non-null  object
 27  Diag 28 Secundario (cod+des)    14561 non-null  object
 28  Diag 29 Secundario (cod+des)    14561 non-null  object
 29  Diag 30 Secundario (cod+des)    14561 non-null  object
 30  Diag 31 Secundario (cod+des)    14561 non-null  object
 31  Diag 32 Secundario (cod+des)    14561 non-null  object
 32  Diag 33 Secundario (cod+des)    14561 non-null  object
 33  Diag 34 Secundario (cod+des)    14561 non-null  object
 34  Diag 35 Secundario (cod+des)    14561 non-null  object
 35  Proced 01 Principal (cod+des)   14561 non-null  object
 36  Proced 02 Secundario (cod+des)  14561 non-null  object
 37  Proced 03 Secundario (cod+des)  14561 non-null  object
 38  Proced 04 Secundario (cod+des)  14561 non-null  object
 39  Proced 05 Secundario (cod+des)  14561 non-null  object
 40  Proced 06 Secundario (cod+des)  14561 non-null  object
 41  Proced 07 Secundario (cod+des)  14561 non-null  object
 42  Proced 08 Secundario (cod+des)  14561 non-null  object
 43  Proced 09 Secundario (cod+des)  14561 non-null  object
 44  Proced 10 Secundario (cod+des)  14561 non-null  object
 45  Proced 11 Secundario (cod+des)  14561 non-null  object
 46  Proced 12 Secundario (cod+des)  14561 non-null  object
 47  Proced 13 Secundario (cod+des)  14561 non-null  object
 48  Proced 14 Secundario (cod+des)  14561 non-null  object
 49  Proced 15 Secundario (cod+des)  14561 non-null  object
 50  Proced 16 Secundario (cod+des)  14561 non-null  object
 51  Proced 17 Secundario (cod+des)  14561 non-null  object
 52  Proced 18 Secundario (cod+des)  14561 non-null  object
 53  Proced 19 Secundario (cod+des)  14561 non-null  object
 54  Proced 20 Secundario (cod+des)  14561 non-null  object
 55  Proced 21 Secundario (cod+des)  14561 non-null  object
 56  Proced 22 Secundario (cod+des)  14561 non-null  object
 57  Proced 23 Secundario (cod+des)  14561 non-null  object
 58  Proced 24 Secundario (cod+des)  14561 non-null  object
 59  Proced 25 Secundario (cod+des)  14561 non-null  object
 60  Proced 26 Secundario (cod+des)  14561 non-null  object
 61  Proced 27 Secundario (cod+des)  14561 non-null  object
 62  Proced 28 Secundario (cod+des)  14561 non-null  object
 63  Proced 29 Secundario (cod+des)  14561 non-null  object
 64  Proced 30 Secundario (cod+des)  14561 non-null  object
 65  Edad en años                    14561 non-null  int64
 66  Sexo (Desc)                     14561 non-null  object
 67  GRD                             14561 non-null  object
dtypes: int64(1), object(67)
memory usage: 7.6+ MB

In [5]:
# ==========================================================
# PASO 8. VALORES NULOS
# ==========================================================

nulos = df.isnull().sum().sort_values(ascending=False)
nulos[nulos > 0]

Series([], dtype: int64)

In [7]:
# Ver estadísticas principales de la edad
print(df['Edad en años'].describe())

# Buscar si existen valores fuera de rango lógico (ejemplo: menores a 0 o mayores a 110)
outliers_edad = df[(df['Edad en años'] < 0) | (df['Edad en años'] > 110)]
print(f"\nCantidad de registros con edad fuera de rango: {len(outliers_edad)}")
df['Sexo (Desc)'].value_counts()

count    14561.000000
mean        39.426550
std         24.681545
min          0.000000
25%         23.000000
50%         36.000000
75%         60.000000
max        121.000000
Name: Edad en años, dtype: float64

Cantidad de registros con edad fuera de rango: 1

Sexo (Desc)
Mujer     9617
Hombre    4944
Name: count, dtype: int64

In [10]:
import pandas as pd
import numpy as np

# ==========================================================
# REPORTE TÉCNICO: COMPLETITUD Y CORRECTITUD (FASE 1)
# ==========================================================

def reporte_calidad_datos(df):
    print("=== ESTUDIO DE CALIDAD DE DATOS (DATA QUALITY ASSESSMENT) ===\n")

    # 1. EVALUACIÓN DE COMPLETITUD (Nulos Técnicos vs Semánticos)
    nulos_tecnicos = df.isnull().sum().sum()
    nulos_semanticos = (df == "-").sum().sum() # Los guiones que detectamos antes
    total_celdas = df.size

    print(f"--- 1. COMPLETITUD ---")
    print(f"- Registros Totales: {len(df)}")
    print(f"- Columnas Totales: {len(df.columns)}")
    print(f"- Valores Nulos (NaN): {nulos_tecnicos}")
    print(f"- Valores Sin Información ('-'): {nulos_semanticos}")
    print(f"- Completitud Real: {((total_celdas - nulos_semanticos) / total_celdas) * 100:.2f}%")
    print("Nota: El dataset no tiene nulos técnicos, pero usa '-' en diagnósticos secundarios.\n")

    # 2. VALIDACIÓN DE RANGOS: EDAD
    print(f"--- 2. CORRECTITUD: RANGOS DE EDAD ---")
    edad_min = df['Edad en años'].min()
    edad_max = df['Edad en años'].max()
    print(f"- Rango detectado: [{edad_min} - {edad_max}] años")

    # Criterio de Ingeniería: Edades negativas o sobre 110 años
    fuera_rango = df[(df['Edad en años'] < 0) | (df['Edad en años'] > 110)]
    print(f"- Registros fuera de rango lógico (0-110 años): {len(fuera_rango)}")
    if len(fuera_rango) > 0:
        print(f"  * Acción: Se identifica outlier de {edad_max} años para tratamiento en pre-procesamiento.")
    print("")

    # 3. VALIDACIÓN DE CATEGORÍAS: SEXO
    print(f"--- 3. CORRECTITUD: CATEGORÍAS DE SEXO ---")
    categorias_sexo = df['Sexo (Desc)'].unique()
    print(f"- Categorías encontradas: {categorias_sexo}")

    conteo_sexo = df['Sexo (Desc)'].value_counts()
    print("- Frecuencias:")
    for cat, val in conteo_sexo.items():
        print(f"  * {cat}: {val} registros")

    # Verificación de consistencia
    if len(categorias_sexo) <= 2:
        print("  * Validación: No se detectan errores de digitación en la variable Sexo.")
    else:
        print("  * Alerta: Se detectan más de 2 categorías, revisar posibles errores de ingreso.")

# Ejecutar el reporte
reporte_calidad_datos(df)

=== ESTUDIO DE CALIDAD DE DATOS (DATA QUALITY ASSESSMENT) ===

--- 1. COMPLETITUD ---
- Registros Totales: 14561
- Columnas Totales: 68
- Valores Nulos (NaN): 0
- Valores Sin Información ('-'): 649545
- Completitud Real: 34.40%
Nota: El dataset no tiene nulos técnicos, pero usa '-' en diagnósticos secundarios.

--- 2. CORRECTITUD: RANGOS DE EDAD ---
- Rango detectado: [0 - 121] años
- Registros fuera de rango lógico (0-110 años): 1
  * Acción: Se identifica outlier de 121 años para tratamiento en pre-procesamiento.

--- 3. CORRECTITUD: CATEGORÍAS DE SEXO ---
- Categorías encontradas: ['Hombre' 'Mujer']
- Frecuencias:
  * Mujer: 9617 registros
  * Hombre: 4944 registros
  * Validación: No se detectan errores de digitación en la variable Sexo.